name: Tag
description: Introduces a Tag multipalyer minigame to the server. 
version: 0.8.0
main: org.aurora.tag.Tag
authors: ["RussianMushroom"]

commands:
  tag:
    description: 
  
permissions:
  tag.start:
    default: op
  tag.stop:
    default: op
  tag.join:
    default: op
  tag.help:
    default: op
  tag.leave:
    default: op
  tag.set:
    default: op
  tag.leaderboard:
    default: op