name: Tag
description: Introduces a Tag multiplayer minigame to the server. 
version: 1.5.9
main: org.aurora.tag.Tag
authors: ["RussianMushroom"]

commands:
  tag:
    description: 
  
permissions:
  tag.start:
    default: op
  tag.stop:
    default: op
  tag.join:
    default: false
  tag.help:
    default: false
  tag.leave:
    default: false
  tag.set:
    default: op
  tag.leaderboard:
    default: false
  tag.createarena:
    default: op
  tag.listarena:
    default: false
  tag.status:
    default: false