name: Tag
version: 0.6.0
main: org.aurora.tag.Tag
commands:
  tag:
   description: Tag command.
   
permissions:
  tag.start:
    default: op
  tag.stop:
    default: op
  tag.join:
    default: op
  tag.help:
    default: op
  tag.leave:
    default: op
    